### ISSUE TITLE
GWT build fails

### ISSUE THREAD

**Issue by btd-f-lago** [libgdx/ashley#135]
Currently GWT build is failing with error:
(Family.java)
[ERROR] Line 157: @SafeVarargs annotation cannot be applied to non-final instance method all

Javadoc states that SafeVarargs annotated method must be either static or final.
I wonder if this annotation is necessary for GWT to compile?

**Comment by Metaphore** [comment]
Same story...

**Comment by btd-f-lago** [comment]
This is happening from 1.3.3 and does not happen with 1.3.2.

**Comment by pszalanski** [comment]
Ich have the exact same error now, although I have the version which contains this fix. Do you have any idea how that is possible?

**Error log**
```bash
>>>gradlew :html:assemble
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:html:compileJava UP-TO-DATE
:html:processResources UP-TO-DATE
:html:classes UP-TO-DATE
:html:addSource
:html:compileGwt
Mai 05, 2015 6:24:04 PM java.util.prefs.WindowsPreferences <init>
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Compiling module de.oneupmedia.games.riseofmana.GdxDefinition
   Validating units:
      [ERROR] Errors in 'com/badlogic/ashley/core/Family.java'
         [ERROR] Line 126: @SafeVarargs annotation cannot be applied to non-final instance method all
         [ERROR] Line 136: @SafeVarargs annotation cannot be applied to non-final instance method one
         [ERROR] Line 146: @SafeVarargs annotation cannot be applied to non-final instance method exclude
      [ERROR] Errors in 'file:/C:/rise-of-mana/core/src/de/oneupmedia/games/riseofmana/RiseOfMana.java'
         [ERROR] Line 57: The method format(String, int, float) is undefined for the type String
   [ERROR] Aborting compile due to errors in some input files
:html:compileGwt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':html:compileGwt'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.333 secs
```

**Project gradle file**
```gradle
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
    }
    dependencies {
        classpath 'de.richsource.gradle.plugins:gwt-gradle-plugin:0.6'
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'org.robovm:robovm-gradle-plugin:1.0.0'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = 'Rise Of Mana'
        gdxVersion = '1.5.6'
        roboVMVersion = '1.0.0'
        box2DLightsVersion = '1.3'
        ashleyVersion = '1.4.0'
        aiVersion = '1.5.0'
    }

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-tools:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-desktop:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-platform:$gdxVersion:natives-desktop"
    }
}

project(":android") {
    apply plugin: "android"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86"
        compile "com.badlogicgames.ashley:ashley:$ashleyVersion"
        compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion"
        compile "com.badlogicgames.gdx:gdx-ai:$aiVersion"
        compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-android:$gdxVersion"
    }
}

project(":ios") {
    apply plugin: "java"
    apply plugin: "robovm"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "org.robovm:robovm-rt:${roboVMVersion}"
        compile "org.robovm:robovm-cocoatouch:${roboVMVersion}"
        compile "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
        natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-ios"
    }
}

project(":html") {
    apply plugin: "gwt"
    apply plugin: "war"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-box2d-gwt:$gdxVersion:sources"
        compile "com.badlogicgames.ashley:ashley:$ashleyVersion:sources"
        compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion:sources"
        compile "com.badlogicgames.gdx:gdx-ai:$aiVersion:sources"
        compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion:sources"
        compile "com.badlogicgames.gdx:gdx-controllers-gwt:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-controllers-gwt:$gdxVersion:sources"
        compile "com.kotcrab.vis:vis-ui:0.7.4:sources"
    }
}

project(":core") {
    apply plugin: "java"


    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
        compile "com.badlogicgames.ashley:ashley:$ashleyVersion"
        compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion"
        compile "com.badlogicgames.gdx:gdx-ai:$aiVersion"
        compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
        compile "com.kotcrab.vis:vis-ui:0.7.4"
    }
}

tasks.eclipse.doLast {
    delete ".project"
}
```

**Comment by Metaphore** [comment]
Yeah, it's really broken now in 1.4.0 (#156). But have been fixed in current sources. 
I'm wondering, @saltares when it will be new release with this changes?

**Comment by saltares** [comment]
Mmmm, I'll try to make a release this week because I'll be away during the weekend.

**Comment by pigiuz** [comment]
Hi, I'm still getting the same issue, any plan to make a release?

**Comment by saltares** [comment]
@pigiuz which version are you using? The latest is [1.5.0](https://github.com/libgdx/ashley/releases/tag/ashley-1.5.0), 1.5.0 fixed GWT issues. could you please confirm?

**Comment by pigiuz** [comment]
@saltares fixed, I was using 1.4.0 (shame on me)

**Comment by bussiere** [comment]
Same here with 1.6.1 and the desktop version work :+1: 

	Compiling module com.mygdx.game.GdxDefinition
	   Validating units:
	      [ERROR] Errors in 'jar:file:/home/bussiere/.gradle/caches/modules-2/files-2.1/com.badlogicgames.ashley/ashley/1.4.0/2dfd33c58150d135a1b8b14a76d6d79d6252a329/ashley-1.4.0-sources.jar!/com/badlogic/ashley/core/Family.java'
	         [ERROR] Line 126: @SafeVarargs annotation cannot be applied to non-final instance method all
	         [ERROR] Line 136: @SafeVarargs annotation cannot be applied to non-final instance method one
	         [ERROR] Line 146: @SafeVarargs annotation cannot be applied to non-final instance method exclude
	   [ERROR] Aborting compile due to errors in some input files
	:html:compileGwt FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':html:compileGwt'.
	> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED
